// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Player(src string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Player_d1f3`,
		Function: `function __templ_Player_d1f3(src){document.querySelector("#video").pause();
  if (Hls.isSupported()) {
    hls.loadSource(src);
    hls.attachMedia(document.querySelector("#video"));
  } else if (
    document
      .querySelector("#video")
      .canPlayType("application/vnd.apple.mpegurl")
  ) {
    document.querySelector("#video").src = src;
  }
}`,
		Call:       templ.SafeScript(`__templ_Player_d1f3`, src),
		CallInline: templ.SafeScriptInline(`__templ_Player_d1f3`, src),
	}
}
